version: '3.8'
services:
  web:
    container_name: nextjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    links:
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:7.0'
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

volumes:
  postgres:
    name: poke-db
  cache:
    driver: local
